config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :experts, only: %i[index new create] do
    resources :requests, only: %i[new create] do
      resources :offers, only: %i[create update] do
        resources :reviews, only: %i[new create]
      end
    end
  end

  # this is for "my requests", the index of user's request
  resources :requests, only: %i[index], as: "my_requests"

  # this is for "my requests", the show page of user's request
  resources :requests, only: %i[show] do
    resources :messages, only: :create
    patch "/offers/accept/:id", to: "offers#accept", as: "offer_accepted"
    patch "/offers/decline/:id", to: "offers#decline", as: "offer_declined"
  end

  # this is for "requests received", the index of all requests an expert received
  get "requests_received", to: "requests#requests_received"

  # this is for "requests received", the show of each request an expert received
  get "requests_received/:id", to: "requests#requests_received_show", as: "request_received"

  patch "reject/:id", to: "requests#reject", as: "request_rejected"
  delete "requests_rejected/:id", to: "requests#destroy_rejected_request", as: "destroy_rejected_request"

  patch "cancel/:id", to: "requests#cancel", as: "request_cancelled"
  delete "requests_cancelled/:id", to: "requests#destroy_cancelled_request", as: "destroy_cancelled_request"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-box">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logowhite.png" %>
      <% end %>

      <%= link_to root_path, class: "masterymate-link" do %>
        <p id="masterymate"><strong>M</strong>ASTERY<strong>M</strong>ATE</p>
      <% end %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <% if current_user.expert %>
              <div class="nav-item">
                <i class="fa-solid fa-inbox"></i>
                <%= link_to "Requests received", "/requests_received", class: "nav-link" %>
              </div>
              <div class="nav-item nav-link"> | </div>
            <% end %>

            <div class="nav-item">
              <i class="fa-solid fa-table-list"></i>
              <%= link_to "My requests", my_requests_path, class: "nav-link" %>
            </div>

            <div class="nav-item nav-link"> | </div>

            <div class="nav-item">
              <i class="fa-solid fa-users"></i>
              <%= link_to "Browse experts", experts_path, class: "nav-link" %>
            </div>

            <div class="nav-item dropdown">
              <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= cl_image_tag current_user.photo.key, class:"avatar"%>
              </a>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <% if !current_user.expert %>
                  <div class="nav-item">
                    <%= link_to "Become an expert", "/experts/new", class: "dropdown-item" %>
                  </div>
                <% end %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </div>

          <% else %>
            <div class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>