config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :experts, only: %i[index new create] do
    resources :requests, only: %i[new create] do
      resources :offers, only: %i[create update] do
        resources :reviews, only: %i[new create]
      end
    end
  end

  # this is for "my requests", the index of user's request
  resources :requests, only: %i[index], as: "my_requests"

  # this is for "my requests", the show page of user's request
  resources :requests, only: %i[show] do
    resources :messages, only: :create
    patch "/offers/accept/:id", to: "offers#accept", as: "offer_accepted"
    patch "/offers/decline/:id", to: "offers#decline", as: "offer_declined"
  end

  # this is for "requests received", the index of all requests an expert received
  get "requests_received", to: "requests#requests_received"

  # this is for "requests received", the show of each request an expert received
  get "requests_received/:id", to: "requests#requests_received_show", as: "request_received"

  patch "reject/:id", to: "requests#reject", as: "request_rejected"
  delete "requests_rejected/:id", to: "requests#destroy_rejected_request", as: "destroy_rejected_request"

  patch "cancel/:id", to: "requests#cancel", as: "request_cancelled"
  delete "requests_cancelled/:id", to: "requests#destroy_cancelled_request", as: "destroy_cancelled_request"
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :expert
  has_one :offer, dependent: :destroy
  has_many_attached :pictures
  has_many :messages, dependent: :destroy

  STATUS = ["Pending", "Offer made", "Offer declined", "Offer accepted", "Cancelled", "Rejected"]
  validates :title, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { minimum: 25 }
  validates :status, inclusion: { in: STATUS }

  def tag_color
    if self.status == "Pending"
      "yellow"
    elsif self.status == "Offer made"
      "blue"
    elsif self.status == "Offer accepted"
      "green"
    else
      "red"
    end
  end

  def update_date
    x = (Date.today - self.updated_at.to_date).to_i
    if x == 0
      "Today"
    elsif x == 1
      "Yesterday"
    elsif x <= 30
      "#{x} days ago"
    else
      self.updated_at.strftime("%B %d, %Y")
    end
  end

  def create_date
    x = (Date.today - self.created_at.to_date).to_i
    if x == 0
      "Today"
    elsif x == 1
      "Yesterday"
    elsif x <= 30
      "#{x} days ago"
    else
      self.created_at.strftime("%B %d, %Y")
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_user_request, only: %i[index show]
  before_action :set_expert_request, only: %i[requests_received requests_received_show]

  # my resquests > index, for USER
  def index
    # before action
  end

  # my resquests > show, for USER
  def show
    # before action
    @request = Request.find(params[:id])
    @message = Message.new
  end

  # requests received" > index, for EXPERT
  def requests_received
    # before action
  end

  # requests received" > show, for EXPERT
  def requests_received_show
    # before action
    @request = Request.find(params[:id])
    @message = Message.new
    @expert = @request.expert

    if @request.offer.present? && (@request.status == "Offer made" || @request.status == "Offer declined")
      @offer = @request.offer
    else
      @offer = Offer.new
    end
  end

  def new
    @request = Request.new
    @expert = Expert.find(params[:expert_id])
  end

  def create
    @request = Request.new(request_params)
    @expert = Expert.find(params[:expert_id])
    @request.expert = @expert
    @request.user = current_user
    @request.address = current_user.address
    if @request.save
      redirect_to request_path(@request), notice: "The expert has been notified."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def reject
    @request = Request.find(params[:id])
    @request.update(status: "Rejected")
    @request.save
    redirect_to requests_received_path, notice: "The request has been rejected."
  end

  def destroy_rejected_request
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to my_requests_path, status: :see_other, notice: "The request has been deleted."
  end

  def cancel
    @request = Request.find(params[:id])
    @request.update(status: "Cancelled")
    @request.save
    redirect_to my_requests_path, notice: "The request has been cancelled."
  end

  def destroy_cancelled_request
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_received_path, status: :see_other, notice: "The request has been deleted."
  end

  private

  def request_params
    params.require(:request).permit(:title, :description, :estimated_time, :address, pictures: [])
  end

  # refactor
  def set_user_request
    all_requests = Request.where(user: current_user).order(updated_at: :desc)
    @rejected_requests = all_requests.where(status: "Rejected")
    @cancelled_requests = all_requests.where(status: "Cancelled")
    @past_requests = all_requests.select { |request| request.offer.occurs_on.to_date < Date.today if request.status == "Offer accepted" }
    @pending_requests = all_requests - @rejected_requests - @cancelled_requests - @past_requests
  end

  def set_expert_request
    all_requests = Request.where(expert: current_user.expert).order(updated_at: :desc)
    @rejected_requests = all_requests.where(status: "Rejected")
    @cancelled_requests = all_requests.where(status: "Cancelled")
    @past_requests = all_requests.select { |request| request.offer.occurs_on.to_date < Date.today if request.status == "Offer accepted" }
    @pending_requests = all_requests - @rejected_requests - @cancelled_requests - @past_requests
  end
end

app/views/requests/_1my_request.html.erb
<p>Here we should display the descrition of the request, the pictures, the expert contacted, ...</p>

app/views/requests/_1request.html.erb
<h4 class="step-box-title"><%= @request.title %></h4>
<div class="scroll scroll-step1">

  <p><em>Creation date: <%= @request.create_date %></em></p>

  <p><%= @request.description %></p>

  <% @request.pictures.each do |picture| %>
    <%= cl_image_tag picture.key, height: 250 %>
  <% end %>
</div>

<% if @request.status != "Offer accepted" %>
  <p class="decline-label"><em>Did you find another expert or do you no longer need this?</em></p>
  <%= link_to "Cancel request", request_cancelled_path(@request), data: {turbo_method: "patch", turbo_confirm: "Are you sure you want to cancel this request? It will no longer appear on the list."}, class: "my-btn sec" %>
<% end %>

app/views/requests/_2chat.html.erb
<div class="chatroom"
data-controller="chatroom-subscription"
data-chatroom-subscription-request-id-value="<%= @request.id %>"
data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

  <div class="chat-title">
    <h4><%= @request.title %></h4>

    <% if @request.user == current_user %>
      <p>Talking to <%= @request.expert.user.first_name %></p>
    <% elsif @request.expert.user == current_user %>
      <p>Talking to <%= @request.user.first_name %></p>
    <% end %>
  </div>

  <hr class="light-hr">

  <div class="scroll scroll-step2" data-chatroom-subscription-target="messages">
    <% @request.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>

  <hr class="light-hr">

  <%= simple_form_for [@request, @message], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex input-messages"} do |f| %>
    <%= f.input :content,
      label: false,
      placeholder: "Start to chat",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "my-btn prim mb-4 ms-2" %>
  <% end %>
</div>

app/views/requests/_3offer.html.erb
<% if @request.offer.present? %>
  <h4 class="step-box-title"><%= @request.title %>: offer from <%= @request.expert.user.first_name %></h4>
  <div class="scroll scroll-step3">

    <p><%= @request.offer.content %></p>

    <p><strong>Appointement: </strong><%= @request.offer.occurs_on.strftime("%B %d, %Y") %></p>
    <p class="me-5"><strong>Duration: </strong><%= @request.offer.time %>h</p>

    <div class="d-flex">
      <p class="me-4"><strong>Total price: <%= (request.offer.time * request.expert.price_per_hour) + request.offer.extra_costs - request.offer.reduction %>€</strong></p>
      <p class="me-4">Price per hour: <%= @request.expert.price_per_hour %>€</p>
      <p class="me-4">Extra costs: <%= @request.offer.extra_costs %>€</p>
      <p>Reduction: <%= @request.offer.reduction %>€</p>
    </div>
  </div>

  <div class="button-space">
    <% if @request.offer.status == "Offer made" %>
      <%= link_to "Accept offer", request_offer_accepted_path(@request, @request.offer), data: {turbo_method: 'patch'}, class: "my-btn prim" %>
      <%= link_to "Decline offer", request_offer_declined_path(@request, @request.offer), data: {turbo_method: 'patch'}, class: "my-btn sec" %>
    <% end %>
  </div>
  <br>

<% else %>
  <p class="text-center"><%= @request.expert.user.first_name %> did not submit an offer yet 🥲.</p>
  <hr>
<% end %>

app/views/requests/_4contact.html.erb
<% if @request.status == "Offer accepted" %>

    <p class="text-center">Congratulations 🎉 Your appointment with <%= @request.expert.user.first_name %> is confirmed!</p>

    <hr>

    <p><strong>Recap of your appointment</strong></p>
    <p><strong>Date: </strong> to be added</p>
    <p><strong>Address: </strong><%= @request.user.address %></p>

    <hr>

    <p><strong>Contact details</strong></p>
    <p>Please keep them confidential!</p>

    <div class="d-flex align-items-center">

      <%= cl_image_tag @request.expert.user.photo.key, height: 150, class: "avatar-lg" %>

      <div class="ms-3">
        <p><strong>Expert full name: </strong><%= @request.expert.user.first_name %> <%= @request.expert.user.last_name %></p>
        <p><strong>Phone number: </strong>to be added</p>
        <p class="mb-0"><strong>Email: </strong><%= @request.expert.user.email %> </p>
      </div>

    </div>

 <% else %>
        <p class="text-center">Sorry, you'll only have access to the expert contact details once you accept their offer 😊.</p>
         <hr>
    <% end %>

app/views/requests/_4contact_details.html.erb
<p>Here we will see the contact details of the exeprt, the recap of the appointment (date), ...</p>

app/views/requests/_93offer.html.erb
<%# OFFER ACCEPTED: RECAP OF THE OFFER %>
<% if @request.offer.present? && @request.status == "Offer accepted"%>
  <h4 class="step-box-title"><%= @request.title %>: offer to <%= @request.user.first_name %></h4>
  <p>The offer has been accepted, you can no longer edit it 🗝️.</p>

  <div class="scroll scroll-step3">
    <p><strong>Offer recap:</strong></p>
    <p><%= @request.offer.content %></p>

    <p><strong>Appointement: </strong><%= @request.offer.occurs_on.strftime("%B %d, %Y") %></p>
    <p class="me-5"><strong>Duration: </strong><%= @request.offer.time %>h</p>

    <div class="d-flex">
      <p class="me-4"><strong>Total price: <%= (request.offer.time * request.expert.price_per_hour) + request.offer.extra_costs - request.offer.reduction %>€</strong></p>
      <p class="me-4">Price per hour: <%= @request.expert.price_per_hour %>€</p>
      <p class="me-4">Extra costs: <%= @request.offer.extra_costs %>€</p>
      <p>Reduction: <%= @request.offer.reduction %>€</p>
    </div>
  </div>

  <%# NO OFFER OR OFFER MADE: FORM %>
  <%# the logic if we can a new or an edit form is in the request controller %>
<% else %>
  <%= simple_form_for [@expert, @request, @offer], data: { controller: "offer-total-price", offer_total_price_price_value: "#{@request.expert.price_per_hour}" } do |f| %>
    <%= f.input :content, label: "Offer content",
        label_html: { class:"bold-label" },
        hint: "Describe how you can help your client and how you will work together."
    %>

    <%= f.input :occurs_on, label: "Appointment date", label_html: { class:"bold-label mt-3" }, hint: "Align through the chat on a date that works for you and the client!" %>

    <p class="price-title"><strong>Price</strong></p>

    <div class="price-box">
      <div class="inline-3-inputs">
        <%= f.input :time, label: "How long will it take?", input_html: { data: { offer_total_price_target: "numberOfHour", action: "keyup->offer-total-price#updateFields" } }, hint: "Your rate: #{@request.expert.price_per_hour}€/h" %>
        <span class="input-group-text form-input-groups2">h</span>
      </div>

      <div class="inline-3-inputs">
        <%= f.input :extra_costs, input_html: { data: { offer_total_price_target: "extraCosts", action: "keyup->offer-total-price#updateFields" } }, hint: "E.g. for materials" %>
        <span class="input-group-text form-input-groups2">€</span>
      </div>

      <div class="inline-3-inputs">
        <%= f.input :reduction, input_html: { data: { offer_total_price_target: "reduction", action: "keyup->offer-total-price#updateFields" } }, hint: "E.g. discount if many hours" %>
        <span class="input-group-text form-input-groups2">€</span>
      </div>
    </div>

    <% if request.status == "Offer made" || request.status == "Offer declined" %>
      <div class="d-flex">
        <p class="me-2"><strong>Total price:</strong></p>
        <% total_price = @request.expert.price_per_hour * @offer.time + @offer.extra_costs - @offer.reduction %>
        <p data-offer-total-price-target="totalPrice"><%= total_price %></p>
        <p>€</p>
      </div>
    <% elsif request.status == "Pending" %>
      <div class="d-flex">
        <p class="me-2"><strong>Total price:</strong></p>
        <p data-offer-total-price-target="totalPrice">-</p>
        <p>€</p>
      </div>
    <% end %>

    <%= f.submit "Submit", class: "my-btn prim mt-3" %>
  <% end %>
<% end %>

app/views/requests/_94confirmation.html.erb
<% if @request.status == "Offer accepted" %>

  <h4 class="step-box-title">Congratulations!</h4>

  <p>Your appointment with <%= @request.user.first_name %> is confirmed 🎉.</p>

  <br>

  <p><i class="fa-solid fa-calendar-check"></i> <strong>Recap of your appointment</strong></p>
  <p><strong>Date: </strong><%= @request.offer.occurs_on %></p>
  <p><strong>Address: </strong><%= @request.user.address %></p>

  <br>

  <p><i class="fa-solid fa-address-card"></i> <strong>Contact details</strong></p>
  <p>Please keep them confidential!</p>

  <div class="d-flex align-items-center">
      <%= cl_image_tag @request.user.photo.key, height: 150, class: "avatar-lg" %>

      <div class="ms-3">
        <p><strong>Expert full name: </strong><%= @request.user.first_name %> <%= @request.user.last_name %></p>
        <p><strong>Phone number: </strong><%= @request.user.phone_number %></p>
        <p class="mb-0"><strong>Email: </strong><%= @request.user.email %> </p>
      </div>
  </div>

<% else %>
  <p class="text-center">Sorry, you'll only have access to the expert contact details once you accept their offer 😊.</p>
  <hr>
<% end %>

app/views/requests/_requests_received.html.erb
<div class="my-requests-box">

  <%# PENDING REQUESTS TABLE %>
  <h3>Pending requests</h3>

  <div class="requests-table">

    <div class="titles">
      <p class="col1-size">Request</p>
      <p class="col2-size">Client</p>
      <p class="col3-size">Last update <i class="fa-solid fa-sort-down"></i></p>
      <p class="col4-size pe-2">Status</p>
    </div>

    <div class="lines">

      <% if @pending_requests.nil? || @pending_requests.empty? %>
        <div class="text-center">
          <br><br>
          <p class="py-0">Oh no... You don't have any requests.</p>
          <p class="py-0">Be patient, customers will arrive anytime!</p>
          <br>
          <%= image_tag "cat.gif", class:"cat-gif" %>
          <br><br><br>
        </div>

      <% else %>

        <% counter = 0 %>
        <% @pending_requests.each do |request| %>
          <% counter += 1 %>
          <% if counter % 2 == 1
            pair_or_impair = "impair"
          else
            pair_or_impair = "pair"
          end %>

          <%= link_to request_received_path(request) do %>
            <div class="line <%= pair_or_impair %> <%= params[:id].to_i == request.id ? "line-active" : "" %>">
              <p class="col1-size"><%= request.title %></p>
              <p class="col2-size"><%= request.user.first_name %></p>
              <p class="col3-size"><%= request.update_date %></p>
              <div class="col4-size d-flex justify-content-end">
                <p class="status-tag <%= request.tag_color %>"><%= request.status %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <%# CANCELLED REQUESTS TABLE %>
  <% unless @cancelled_requests.nil? || @cancelled_requests.empty? %>
    <br><br>
    <h3>Cancelled requests</h3>

    <div class="requests-table">
      <div class="titles">
        <p class="col1-size">Request</p>
        <p class="col2-size">Client</p>
        <p class="col3-size">Last update <i class="fa-solid fa-sort-down"></i></p>
      </div>

      <% counter = 0 %>

      <% @cancelled_requests.each do |request| %>
        <% counter += 1 %>
        <% if counter % 2 == 1
          pair_or_impair = "impair"
        else
          pair_or_impair = "pair"
        end %>

        <div class="line-no-hover <%= pair_or_impair %> <%= params[:id].to_i == request.id ? "line-active" : "" %>">
          <p class="col1-size"><%= request.title %></p>
          <p class="col2-size"><%= request.user.first_name %></p>
          <p class="col3-size"><%= request.update_date %></p>

          <div class="col4-size d-flex justify-content-end">
            <%= link_to destroy_cancelled_request_path(request), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-regular fa-trash-can"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <%# PAST OFFERS TABLE %>
  <% unless @past_requests.nil? || @past_requests.empty? %>
    <br><br>
    <h3>Past jobs</h3>

    <div class="requests-table">

      <div class="titles">
        <p class="col1-size">Request request</p>
        <p class="col2-size">Client</p>
        <p class="col3-size">Delivery date <i class="fa-solid fa-sort-down"></i></p>
      </div>

      <div class="lines">
        <% counter = 0 %>

        <% @past_requests.each do |request| %>
          <% counter += 1 %>
          <% if counter % 2 == 1
            pair_or_impair = "impair"
          else
            pair_or_impair = "pair"
          end %>

          <%= link_to request_received_path(request) do %>
            <div class="line <%= pair_or_impair %> <%= params[:id].to_i == request.id ? "line-active" : "" %>">
              <p class="col1-size"><%= request.title %></p>
              <p class="col2-size"><%= request.user.first_name %></p>
              <p class="col3-size"><%= request.offer.occurs_on.strftime("%B %d, %Y") %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/requests/index.html.erb
<div class="requests-overview">
  <div class="container-fluid my-requests-container">
    <%= render "my_requests" %>
  </div>

  <div class="container-fluid request-steps-container">
    <div class="request-steps-box empty-box">
      <p>Click on a request to see more details!</p>
      <%= image_tag "click.gif", class:"click-gif" %>
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="container form-container medium-form">
  <h2>Contact <%= @expert.user.first_name %></h2>
  <%= simple_form_for [@expert, @request] do |f| %>
       <div class="mb-3 string required request_title" data-controller="character-count">
        <label class="form-label string required" for="request_title">Subject <abbr title="required">*</abbr></label>
        <input class="form-control string required" type="text" name="request[title]" id="request_title" data-action="keyup->character-count#countdown">
        <div class="form-text" data-character-count-target="hint">30 characters left</div>
      </div>
    <%= f.input :description, placeholder: "What do you want to achieve? How much time do you want to devote to this?" %>
    <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Create request", class:"my-btn prim" %>
  <% end %>
</div>

<br><br><br>

app/views/requests/requests_received.html.erb
<div class="requests-overview">
  <div class="container-fluid my-requests-container">
    <%= render "requests_received" %>
  </div>

  <div class="container-fluid request-steps-container">
    <div class="request-steps-box empty-box">
      <p>Click on a request to see more details!</p>
      <%= image_tag "click.gif", class:"click-gif" %>
    </div>
  </div>
</div>

app/views/requests/requests_received_show.html.erb
<div class="requests-overview">
  <div class="container-fluid my-requests-container">
    <%= render "requests_received" %>
  </div>

  <div class="container-fluid request-steps-container">
    <div class="request-steps-box" data-controller="steps">

      <div class="steps-buttons">
        <button class="step-button <%= @request.status == "Pending" ? "active-step" : "" %>" data-action="click->steps#display1" data-steps-target="button1">Client request</button>
        <i class="fa-solid fa-angle-right"></i>
        <button class="step-button" data-action="click->steps#display2" data-steps-target="button2">Chat</button>
        <i class="fa-solid fa-angle-right"></i>
        <button class="step-button <%= (@request.status == "Offer made" || @request.status == "Offer declined") ? "active-step" : "" %>" data-action="click->steps#display3" data-steps-target="button3">Offer</button>
        <i class="fa-solid fa-angle-right <%= @request.offer.present? && @request.status == "Offer accepted" ? "" : "grey-arrow" %>"></i>
        <button class="step-button <%= @request.status == "Offer accepted" ? "active-step" : "" %> <%= @request.offer.present? && @request.status == "Offer accepted" ? "" : "blocked" %>" data-action="click->steps#display4" data-steps-target="button4">Confirmation</button>
      </div>

      <div class="<%= @request.status == "Pending" ? "" : "d-none" %>" data-steps-target="render1"><%= render "91request", request: @request %></div>
      <div class="d-none" data-steps-target="render2"><%= render "2chat", request: @request %></div>
      <div class="<%= (@request.status == "Offer made" || @request.status == "Offer declined") ? "" : "d-none" %>" data-steps-target="render3"><%= render "93offer", request: @request, offer: @offer %></div>
      <div class="<%= @request.status == "Offer accepted" ? "" : "d-none" %>" data-steps-target="render4"><%= render "94confirmation", request: @request %></div>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<div class="requests-overview">
  <div class="container-fluid my-requests-container">
    <%= render "my_requests" %>
  </div>

  <div class="container-fluid request-steps-container">
    <div class="request-steps-box" data-controller="steps">

      <div class="steps-buttons">
        <button class="step-button <%= @request.status == "Pending" ? "active-step" : "" %>" data-action="click->steps#display1" data-steps-target="button1">My request</button>
        <i class="fa-solid fa-angle-right"></i>
        <button class="step-button" data-action="click->steps#display2" data-steps-target="button2">Chat</button>
        <i class="fa-solid fa-angle-right <%= @request.offer.present? ? "" : "grey-arrow" %>"></i>
        <button class="step-button <%= (@request.status == "Offer made" || @request.status == "Offer declined") ? "active-step" : "" %> <%= @request.offer.present? ? "" : "blocked" %>" data-action="click->steps#display3" data-steps-target="button3">Offer</button>
        <i class="fa-solid fa-angle-right <%= @request.offer.present? && @request.status == "Offer accepted" ? "" : "grey-arrow" %>"></i>
        <button class="step-button <%= @request.status == "Offer accepted" ? "active-step" : "" %> <%= @request.offer.present? && @request.status == "Offer accepted" ? "" : "blocked" %>" data-action="click->steps#display4" data-steps-target="button4">Confirmation</button>
      </div>

      <div class="<%= @request.status == "Pending" ? "" : "d-none" %>" data-steps-target="render1"><%= render "1request", request: @request %></div>
      <div class="d-none" data-steps-target="render2"><%= render "2chat", request: @request %></div>
      <div class="<%= (@request.status == "Offer made" || @request.status == "Offer declined") ? "" : "d-none" %>" data-steps-target="render3"><%= render "3offer", request: @request %></div>
      <div class="<%= @request.status == "Offer accepted" ? "" : "d-none" %>" data-steps-target="render4"><%= render "4confirmation", request: @request %></div>
    </div>
  </div>
</div>