config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :experts, only: %i[index new create] do
    resources :requests, only: %i[new create] do
      resources :offers, only: %i[create update] do
        resources :reviews, only: %i[new create]
      end
    end
  end

  # this is for "my requests", the index of user's request
  resources :requests, only: %i[index], as: "my_requests"

  # this is for "my requests", the show page of user's request
  resources :requests, only: %i[show] do
    resources :messages, only: :create
    patch "/offers/accept/:id", to: "offers#accept", as: "offer_accepted"
    patch "/offers/decline/:id", to: "offers#decline", as: "offer_declined"
  end

  # this is for "requests received", the index of all requests an expert received
  get "requests_received", to: "requests#requests_received"

  # this is for "requests received", the show of each request an expert received
  get "requests_received/:id", to: "requests#requests_received_show", as: "request_received"

  patch "reject/:id", to: "requests#reject", as: "request_rejected"
  delete "requests_rejected/:id", to: "requests#destroy_rejected_request", as: "destroy_rejected_request"

  patch "cancel/:id", to: "requests#cancel", as: "request_cancelled"
  delete "requests_cancelled/:id", to: "requests#destroy_cancelled_request", as: "destroy_cancelled_request"
end

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1><strong>Connect. Learn. Do.</strong></h1>
    <h2>Transform tasks into talents with <strong>MasteryMate</strong></h2>

    <%= form_with url: experts_path, method: :get, class:"search-bar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control mx-1",
        placeholder: "What do you want to learn?"
      %>
      <button type="submit" name="" class="my-btn prim search-btn mx-1">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    <% end %>
  </div>
</div>

<div class="container padding">
  <div class="masterymate-home-infos">
    <div class="about-masterymate">
      <h3>Why choose MasteryMate?</h3>
      <p>Designed for <b>young adults</b> eager to learn and tackle <b>home tasks</b>, MasteryMate connects you with <b>local experts</b> ready to share their knowledge.</p>
      <p>
      <b>Empower yourself</b>—from fixing a leaky faucet to mastering culinary delights and DIY projects. MasteryMate is with you, every step.
      </p>
    </div>

    <div class="register-as-expert">
      <h3>Register as an expert!</h3>
      <p><b>Share your skills</b> and <b>impact your community</b> — join MasteryMate!</p>
      <p>As an expert, <b>earn while you empower</b> others with hands-on learning. Register now to turn your passion into purpose.</p>
      <div class="d-flex justify-content-end">
        <%= link_to "Start now!", new_expert_path, class: "my-btn prim" %>
      </div>
    </div>
  </div>

  <h3 class="mt-3 mb-2">Popular experts</h3>

  <div class="row">
    <% @experts.take(3).each do |expert| %>
      <div class="col-4">
        <div class="expert-card">
          <div class="pic-position">
            <%= cl_image_tag expert.user.photo.key, class:"expert-img" %>

            <div class="card-tags">
              <% expert.fields.each do |field| %>
                <div><p class="card-tag"><%= field.expertise %></p></div>
              <% end %>
            </div>
          </div>

          <div class="expert-card-text">
            <div class="name-price mb-0">
              <h4><%= expert.user.first_name %></h4>
              <p><%= expert.price_per_hour %>€/h</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <h3 class="mt-3 mb-2">They say it!</h3>

  <div class="comments mb-5">
    <div class="comment me-4">
      <p>As someone who prefers hands-on learning over watching endless video tutorials, this platform has been a game-changer for me.</p>
      <small>Sophie, MasteryMate user</small>
    </div>

    <div class="comment">
      <p>From the seamless interface to the comprehensive support resources, everything about MasteryMate is designed to ensure both experts and learners have a top-notch experience.</p>
      <small>David, MasteryMate expert</small>
    </div>
  </div>
</div>