config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :experts, only: %i[index new create] do
    resources :requests, only: %i[new create] do
      resources :offers, only: %i[create update] do
        resources :reviews, only: %i[new create]
      end
    end
  end

  # this is for "my requests", the index of user's request
  resources :requests, only: %i[index], as: "my_requests"

  # this is for "my requests", the show page of user's request
  resources :requests, only: %i[show] do
    resources :messages, only: :create
    patch "/offers/accept/:id", to: "offers#accept", as: "offer_accepted"
    patch "/offers/decline/:id", to: "offers#decline", as: "offer_declined"
  end

  # this is for "requests received", the index of all requests an expert received
  get "requests_received", to: "requests#requests_received"

  # this is for "requests received", the show of each request an expert received
  get "requests_received/:id", to: "requests#requests_received_show", as: "request_received"

  patch "reject/:id", to: "requests#reject", as: "request_rejected"
  delete "requests_rejected/:id", to: "requests#destroy_rejected_request", as: "destroy_rejected_request"

  patch "cancel/:id", to: "requests#cancel", as: "request_cancelled"
  delete "requests_cancelled/:id", to: "requests#destroy_cancelled_request", as: "destroy_cancelled_request"
end

app/models/expert.rb
class Expert < ApplicationRecord
  belongs_to :user
  has_many :expert_fields
  has_many :fields, through: :expert_fields
  has_many :requests
  has_many :reviews

  validates :description, presence: true, length: { minimum: 25 }
  validates :price_per_hour, presence: true, numericality: { only_integer: true }
end

app/controllers/experts_controller.rb
class ExpertsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @fields = Field.all
    @experts = Expert.all

    # 1. set the variables (arrows of experts) depending on the different searches
    experts_category = []
    experts_query = []
    experts_distance = []

    if params[:category].present?
      experts_category = @experts.joins(:fields).where(fields: { expertise: params[:category] })
    end

    if params[:query].present?
      experts_query = @experts.where("description ILIKE ?", "%#{params[:query]}%")
    end

    if params[:distance].present?
      users = User.near(current_user.address, params[:distance].to_i)
      users.each { |user| experts_distance << user.expert if user.expert.present? }
    end

    # 2. make the different search scenarios
    if params[:category].present? && params[:query].present? && params[:distance].present?
      @experts = experts_category & experts_query & experts_distance
    elsif params[:category].present? && params[:query].present?
      @experts = experts_category & experts_query
    elsif params[:query].present? && params[:distance].present?
      @experts = experts_query & experts_distance
    elsif params[:category].present? && params[:distance].present?
      @experts = experts_category & experts_distance
    elsif params[:category].present?
      @experts = experts_category
    elsif params[:query].present?
      @experts = experts_query
    elsif params[:distance].present?
      @experts = experts_distance
    end
  end

  def new
    @expert = Expert.new
  end

  def create
    @expert = Expert.new(expert_params)
    @expert.user = current_user
    if @expert.save
      redirect_to experts_path, notice: "Congratulations, your profile is now visible to visitors!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expert_params
    params.require(:expert).permit(:description, :price_per_hour, field_ids: [])
  end
end

app/views/experts/index.html.erb
<div class="container">
  <h1 class="top-title text-center">Meet our experts...</h1>

  <%# FIELD FILTERS %>
  <div class="row justify-content-center">
    <div class="col-9">
      <div class="search-tags">
        <% @fields.each do |field| %>
          <%= link_to field.expertise, experts_path(category: field.expertise), class: "search-tag #{params[:category] == field.expertise ? "search-tag-active" : "" }" %>
        <% end %>
      </div>
    </div>
  </div>

  <%# SEARCH BAR %>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= form_with url: experts_path, method: :get, class:"search-bar" do %>
        <%= text_field_tag :category, params[:category], type: "hidden" %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mx-1",
          placeholder: "Type a keyword"
        %>
        <% if user_signed_in? %>
          <%= number_field_tag :distance,
            params[:distance],
            class: "form-control mx-1 distance-box",
            placeholder: "Type a max distance"
          %>
        <% end %>
        <button type="submit" name="" class="my-btn prim search-btn mx-1" data-controller="loader" data-action="click->loader#spin">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      <% end %>
    </div>
  </div>

  <%# NUMBER OF RESULTS %>
  <div class="results-reset">
    <% if @experts.count == 0
      results = "Sorry... no result"
    elsif @experts.count == 1
      results = "1 result"
    else
      results = "#{@experts.count} results"
    end %>
    <p class="mb-0"><%= results %> | <%= link_to "Reset", experts_path %></p>
  </div>

  <%# CARDS & MODAL %>
  <div class="row">
    <% @experts.each do |expert| %>
      <div class="col-3">

        <%# EXPERT CARDS %>
        <div class="expert-card" data-bs-toggle="modal" data-bs-target="#expertModal<%= expert.id %>">

          <div class="pic-position">
            <%= cl_image_tag expert.user.photo.key, class:"expert-img" %>

            <div class="card-tags">
              <% expert.fields.each do |field| %>
                <div><p class="card-tag"><%= field.expertise %></p></div>
              <% end %>
            </div>
          </div>

          <div class="expert-card-text">
            <div class="name-price">
              <h4><%= expert.user.first_name %></h4>
              <p><%= expert.price_per_hour %>€/h</p>
            </div>
            <% if expert.reviews.present? %>
              <p><%= ((expert.reviews.map(&:rating).sum).fdiv(expert.reviews.count)).round(1) %>
              <%= "⭐️" * ((expert.reviews.map(&:rating).sum).fdiv(expert.reviews.count)) %>
               (<%= expert.reviews.count %>)
              </p>
              <% else %>
              <p class="expert-card-no-review">No review yet</p>
            <% end %>
            <% if user_signed_in? && params[:distance].present? %>
              <p class="mt-2"><i class="fa-solid fa-location-dot"></i> <%= expert.user.distance_to(current_user.address).round(0) %> km</p>
            <% end %>
          </div>
        </div>

        <%# MODAL %>
        <div class="modal fade my-modal" id="expertModal<%= expert.id %>" tabindex="-1" aria-labelledby="expertModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-xl modal-dialog-scrollable">
            <div class="modal-content">

              <%# header %>
              <div class="modal-header"><div class="container-fluid"><div class="row">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

                <div class="col-4">
                  <%= cl_image_tag expert.user.photo.key, class:"modal-expert-img" %>
                </div>

                <div class="col-8">
                  <div class="modal-text">
                    <h4><%= expert.user.first_name %></h4>
                    <% if expert.reviews.present? %>
                      <p><%= ((expert.reviews.map(&:rating).sum).fdiv(expert.reviews.count)).round(1) %>
                      <%= "⭐️" * ((expert.reviews.map(&:rating).sum).fdiv(expert.reviews.count)) %>
                      (<%= expert.reviews.count %>)
                      </p>
                      <% else %>
                      <p class="expert-card-no-review">No review yet</p>
                    <% end %>

                    <p><i class="fa-solid fa-coins"></i> <%= expert.price_per_hour %>€/h</p>

                    <div class="modal-tags">
                      <% expert.fields.each do |field| %>
                        <div><p class="modal-tag"><%= field.expertise %></p></div>
                      <% end %>
                    </div>

                    <p class="grow"><%= expert.description %></p>


                    <div class="btn-position">
                      <%= link_to "Contact #{expert.user.first_name}", new_expert_request_path(expert), class:"my-btn prim" %>
                    </div>
                  </div>
                </div>
              </div></div></div>

              <%# body %>
              <% if expert.reviews.present? %>
                <div class="modal-body ps-4">
                  <% reviews = expert.reviews.order(created_at: :desc) %>

                  <% index = 0 %>


                  <% reviews.each do |review| %>
                    <% if index != 0 %>
                      <hr>
                    <% end %>
                    <% index +=1 %>

                    <div class="reviewer">
                      <%= cl_image_tag review.user.photo.key, class:"avatar" %>
                      <p class="name"><%= review.user.first_name %></p>
                      <%= "⭐️" * review.rating %>
                      <p class="date"><%= review.create_date %></p>
                    </div>
                    <p class="mt-3"><%= review.comment %></p>
                  <% end %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/experts/new.html.erb
<div class="container form-container medium-form">
  <h2>Create your expert profile</h2>

  <%= simple_form_for @expert do |f| %>
    <%= f.input :description, label: "Describe yourself", hint: "Min 25 characters" %>
    <div class="input-group form-alignment">
      <%= f.input :price_per_hour %>
      <span class="input-group-text form-input-groups">€</span>
    </div>
    <%= f.association :fields ,label_method: :expertise, value_method: :id, as: :check_boxes, label: "Expertise" %>
    <%= f.button :submit, "Create profile", class:"my-btn prim" %>
  <% end %>
</div>

<br><br><br>